// Positions use a shared 2D origin at Habitat 05. Only areas need coordinates.
export const locationDefinitions = {
  startId: "habitat",
  connectionDistance: 120,
  types: {
    prospectingSite: { kind: 'site', storage: { capacityM3: 1 }, color: '#26312c', actionSets: ['processing'],
      initialAccess: { public: ['enter', 'dock', 'useFacilities', 'viewCargo', 'depositCargo', 'withdrawCargo'], grants: {} } },
    area: { kind: "area", color: "#181e22" },
    habitat: { kind: "site", storage: { capacityM3: 10 }, color: "#1e2520", actionSets: ["crafting", "equipment", "processing"] },
    platform: { kind: "site", storage: { capacityM3: 2 }, color: "#22221c", actionSets: ["crafting", "equipment", "processing"] },
    derelict: { kind: "site", storage: { capacityM3: 0.25 }, color: "#251e22", actions: ["inspectSite"] },
    ship: { kind: "site", storage: { capacityM3: 0.2 }, mobile: true, color: "#1c2227", actionSets: ["crafting", "equipment", "processing"],
      propulsionCapability: "propulsion", localTravelPowerCost: 1, areaTravelPowerCost: 5,
      localTravelDistance: 10, travelSpeed: 1, initialDockedAtId: null }
  },
  locations: {
    metallicFragment: { name: 'Metallic fragment', type: 'prospectingSite', areaId: 'outerReach', remoteDescription: 'A nearby extraction berth for titanium and rare-earth minerals.', description: 'The berth sits beside titanium-bearing and rare-earth deposits.',
      resourceNodes: [{ id: 'titaniumDeposit', resourceId: 'titaniumOre', initialReserveM3: 1, tags: ['solid', 'prospectable'] }, { id: 'rareEarthDeposit', resourceId: 'rareEarthMinerals', initialReserveM3: 0.5, tags: ['solid', 'prospectable'] }] },
    carbonaceousBody: { name: 'Carbonaceous body', type: 'prospectingSite', areaId: 'outerReach', remoteDescription: 'A berth beside carbon-rich material.', description: 'Carbon-rich deposits supply feedstock for polymers and composites.',
      resourceNodes: [{ id: 'carbonDeposit', resourceId: 'carbonaceousRock', initialReserveM3: 1, tags: ['solid', 'prospectable'] }] },
    denseMetallicBody: { name: 'Dense metallic body', type: 'prospectingSite', areaId: 'outerReach', remoteDescription: 'A berth beside tungsten-bearing ore.', description: 'Dense ore supports heat-resistant machinery and durable tooling.',
      resourceNodes: [{ id: 'tungstenDeposit', resourceId: 'tungstenOre', initialReserveM3: 0.5, tags: ['solid', 'prospectable'] }] },
    icyBody: { name: 'Icy body', type: 'prospectingSite', areaId: 'outerReach', remoteDescription: 'A berth beside water-ice deposits.', description: 'Frozen water-bearing stock can be recovered here.',
      resourceNodes: [{ id: 'iceDeposit', resourceId: 'waterIce', initialReserveM3: 1, tags: ['solid', 'prospectable'] }] },
    vicinity: { name: "Habitat 05 vicinity", type: "area", position: [0, 0],
      remoteDescription: "A sheltered cluster of installations in the inner swarm.",
      description: "Habitat 05 hangs among unfinished collectors. Navigation beacons outline the nearby platforms." },
    outerReach: { name: "Shattered Asteroid", type: "area", position: [40, 0],
      remoteDescription: "A broken asteroid surrounded by mineral-rich fragments and a derelict relay.",
      description: "Fragments of a shattered asteroid drift among silent collectors. Extraction berths and a derelict relay lie within the debris field." },
    habitat: { name: "Habitat 05", type: "habitat", areaId: "vicinity", initialOwnerId: "player",
      narrative:{base:'Habitat 05 is a compact industrial habitat among the unfinished collectors.',dimensions:{origin:['industrial'],scale:['compact']},observableTopics:['local_ship_presence','industrial_activity']},
      resourceNodes: [{ id: 'surfaceMinerals', resourceId: 'siliconMinerals', initialReserveM3: 0.5, tags: ['solid','surface'] }],
      remoteDescription: "Your habitat and fabrication facilities.",
      description: "Habitat 05 is a compact industrial habitat among the unfinished collectors.",
      actions: ["salvage", "gatherElectronics", "gatherMinerals"], shipyard: true,
      startupMessages: [
        { equipment: "solar", healthBelow: 1, conditions: { discoveries: ["structuralFabrication"] },
          text: "Solar array degraded. Salvage metal and fabricate structural parts to repair it." },
        { equipment: "solar", healthBelow: 1, conditions: { not: { discoveries: ["structuralFabrication"] } },
          text: "Solar array degraded. Inspect the damaged structural fitting, salvage metal, and open Research to learn how to fabricate replacement parts. Basic experiments need no power." }
      ],
      initialResources: { power: 8 },
      initialInfrastructure: { solar: { quantity: 1, health: 0.2 }, habitat: { quantity: 1 }, fabricator: { quantity: 1 } },
      sceneObjects: [
        { id: 'reactionWreckage', name: 'Recovered reaction assembly', description: 'A loose drive assembly rests among the local wreckage. Recovery needs space for its 0.80 m³ envelope.',
          effects: [{ type: 'grantItem', itemId: 'basicReactionThruster', amount: 1, destinationId: 'current' }] },
        { id: "collectors", name: "Unfinished collectors", description: "Unfinished mirrors trail into the glare. Their construction stopped long ago." },
        { id: "fitting", name: "Damaged structural fitting", description: "A fractured mounting bracket still shows its original bends and reinforcing ribs. Testing metal scrap at the research bench could reveal how to make a replacement." },
        { id: "solarHardware", name: "Damaged solar hardware", description: "A damaged photovoltaic cell exposes thin silicon layers joined to fine electrical contacts. Comparing minerals with recovered electrical material may explain how to reproduce it." }
      ] },
    supplyPlatform: { name: "Supply platform", type: "platform", areaId: "vicinity", initialOwnerId: "player",
      remoteDescription: "An owned storage platform. No fabrication equipment is installed.",
      description: "The supply platform provides storage space in the Habitat 05 vicinity.",
      narrative:{base:'The supply platform provides storage space in the Habitat 05 vicinity.',observableTopics:['local_ship_presence']},
      capacities: { power: 20 }, initialResources: { power: 2 } },
    derelict: { name: "Derelict relay", type: "derelict", areaId: "outerReach",
      remoteDescription: "An abandoned relay with an accessible observation console.",
      description: "Dust covers the relay console. A frozen construction manifest records the last days of the swarm expansion.",
      narrative:{base:'Dust covers the relay console. A frozen construction manifest records the last days of the swarm expansion.',dimensions:{environment:['dusty']},observableTopics:[]},
      sceneObjects: [{ id: "manifest", name: "Construction manifest", description: "The manifest ends mid-shift. No evacuation order was logged." }] }
  },
  templates: { modularVessel: { name: 'Modular vessel', type: 'ship', modularVessel: true, storage: { capacityM3: 0 }, capacities: { power: 0 },
    description: 'A vessel assembled from installed modules.', remoteDescription: 'A modular vessel.', initialAccess: { public: [], grants: {} } } }
};
